---
- :name: default
  :url: http://monkrb.com/structure
  :repo: git://github.com/monkrb/skeleton.git

- :name: cartilage
  :url: http://github.com/tobyjoe/cartilage/tree/master
  :repo: git://github.com/tobyjoe/cartilage.git

- :name: lazybones
  :url: http://github.com/tobyjoe/lazybones/tree/master
  :repo: git://github.com/tobyjoe/lazybones.git

