---
- :name: default
  :url: http://monkrb.com/structure
  :repo: git://github.com/monkrb/skeleton.git

- :name: cartilage
  :url: http://github.com/tobyjoe/cartilage/tree/master
  :repo: git://github.com/tobyjoe/cartilage.git

- :name: lazybones
  :url: http://github.com/tobyjoe/lazybones/tree/master
  :repo: git://github.com/tobyjoe/lazybones.git

- :name: gerippe
  :url: http://github.com/rkh/gerippe/tree/master
  :repo: git://github.com/rkh/gerippe.git

- :name: armonk
  :url: http://github.com/rkh/gerippe/tree/master
  :url: http://github.com/tizoc/armonk-skeleton/tree/master
  :repo: git://github.com/tizoc/armonk-skeleton.git
